image: ruby:2.4.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - bundle install
          - rake db:setup
          - rake db:test:prepare
          - rspec
        services:
          - postgres
 
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'pipelines' 
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
