defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 32
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host:     <%= ENV["POSTGRES_HOSTNAME"] || 'localhost' %>
  port:     <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *defaults
  database: <%= "#{ENV["POSTGRES_DB"] || 'address_book'}_development" %>

production:
  <<: *defaults

test:
  <<: *defaults
  database: <%= "#{ENV["POSTGRES_DB"] || 'address_book'}_test" %>
